apiVersion: v1
kind: ConfigMap
metadata:
  name: build-pipeline-config
  namespace: build-service
data:
  config.yaml: |
    default-pipeline-name: docker-build
    pipelines:
    - name: fbc-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder@sha256:f8e6a4367bdfefe67ab33f9d8c6bb21634bf7bc27ad380af5e27c6282c70979b
    - name: docker-build
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build@sha256:454cac4f6a5d8a641e34934c1769c48aa74003a0a94d502f265d5c6510e7a1bd
