---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-service-controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        volumeMounts:
          - name: trusted-ca
            mountPath: /etc/pki/ca-trust/extracted/pem/ca-bundle.crt
            subPath: ca-bundle.crt
            readOnly: true
      volumes:
      - name: trusted-ca
        configMap:
          name: trusted-ca
          items:
            - key: ca-bundle.crt
              path: ca-bundle.crt
